import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Rengoku Compendium | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header}>
          <Image src="/logo.png" alt="fire logo" width={50} height={65} />
          <h1>Rengoku Compendium</h1>
        </div>
        <div className={styles.login_container}>
          <h2>Welcome Back</h2>
          <form className={styles.login_form}>
            <input type="text" placeholder="Username" />
            <input type="password" placeholder="Password" />
            <button>Sign In</button>
          </form>
          <div className={styles.navigator}>
            <p>Don&apos;t have an account?</p>
            <Link href="/signup">Sign Up</Link>
          </div>
        </div>
      </main>
    </>
  );
}
